name: Build and Push Docker Image
run-name: ${{ github.actor }} is freaking out over TodoAPI

on: 
  push:
    paths:
      - 'TodoAPI*/**'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - 'TodoAPI*/**'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    
jobs:
  Test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore 
      - name: Build project
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build